#!/bin/sh

## autoload vcs and colors
autoload -Uz vcs_info
autoload -U colors && colors
zstyle ':vcs_info:*' enable git 
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked

precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

function +vi-git-untracked() {
  local -a FLAGS
  FLAGS=('--porcelain')
  FLAGS+='--untracked-files=no'
  if [[ $(git rev-parse --is-inside-work-tree 2>/dev/null) == true ]]; then
    STATUS=$(git status ${FLAGS} 2> /dev/null | tail -n 1)
    if [[ -n $STATUS ]] ; then
      hook_com[misc]="%{$fg_bold[magenta]%}✗"
    else
      hook_com[misc]=""
    fi
  fi
}

zstyle ':vcs_info:*' check-for-changes false
zstyle ':vcs_info:git:*' formats "on %{$fg_bold[cyan]%}%b%m"

# Themes to check
# Robby russell
# AVIT
# muse
# eastwood
# sorin

# Mine
USER="%{$fg[magenta]%}%n%{$reset_color%}"
CURRENT_DIR="%{$fg_bold[blue]%}[%~]%{$reset_color%} "
GIT="\$vcs_info_msg_0_ "
ARROW="%(?:%{$fg_bold[green]%}%B➜%b :%{$fg_bold[red]%}➜ )"
NEWLINE=$'\n'
PROMPT="${CURRENT_DIR}${GIT}${NEWLINE}${ARROW}"
